### ISSUE TITLE
Models Results page has a spelling error on download button

### ISSUE THREAD

**Issue by AmandaCaskenette** [dfrancis01/dfo-richt-project#45]
The download button on the model results page needs to be fixed, currently says "Downlaod Results"

**Comment by dfrancis01** [comment]
This page:
![image](https://user-images.githubusercontent.com/13628072/167926855-f925bfd7-ac10-4653-9bb4-79f9813a9893.png)
This button:
![image](https://user-images.githubusercontent.com/13628072/167926988-2617fdd8-dac2-4fda-8e94-224efe9dffde.png)
